<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Real Time Version Control System</title>
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/js/codemirror/codemirror.js"></script>
    <script type="text/javascript" src="/js/dojo/dojo.js"></script>
    <!--<script type="text/javascript" src="/js/jquery/jquery-1.3.2.min.js"></script>-->
    <script type="text/javascript" src="/js/scripts.js"></script>
</head>