<?php echo $this->render('/layout/head.phtml') ?>
<body>

<div id="left">
<div id="menu">
<?php echo $this->render('/layout/menu.phtml'); ?>
</div>

<div id="navigation">
<?php echo $this->render('/layout/navigation.phtml'); ?>
</div>
</div>

<div id="content">
<?php echo $this->layout()->content; ?>
</div>

<div id="footer">
<?php echo $this->render('/layout/footer.phtml'); ?>
</div>
</body>
</html>
