<div id="navcontainer">
<?php echo $this->escape($this->path) ?>
<ul id="navlist">
<?php if( strlen($this->path) > 0 ) {?>
<li class="updir"><a href="?updir=1">Up dir ..</a>
<?php } ?>
<?php
if( count( $this->files['dirs'] ) > 0 )
    foreach( $this->files['dirs'] as $file )
    {
        echo '<li class="dir"><a href="?dir=' .urlencode( $file ). '">' .$this->escape($file). '</a></li>' ;
    }
if( count( $this->files['files'] ) > 0 )
    foreach( $this->files['files'] as $file )
    {
        echo '<li class="file"><a href="?file=' .urlencode( $file ). '">' .$this->escape($file). '</a></li>' ;
    }
?>
</ul>
<?php echo $this->newFileForm ?>
</div>