<div id="left">
<div id="menu">
<?php if($this->loggedIn) { ?>
<span>User: <?php echo $this->loggedIn->name; ?></span><br />
<?php } ?>
<?php if($this->active) { ?>
<span>Project: <?php echo $this->active->name; ?></span><br />
<?php } ?>
<a href="/user/logout/"><img src="/images/logout.png" alt="Logout" title="Logout" /></a>
<a href="/project/open/"><img src="/images/open.png" alt="Open Project" title="Open Project" /></a>
<a href="#" onclick="showNewFile();"><img src="/images/newfile.png" alt="New file" title="New file" /></a>
<a href="#" onclick="showNewDir();"><img src="/images/newdir.png" alt="New dir" title="New dir" /></a>
<a href="#" onclick="showNewBranch();"><img src="/images/newbranch.png" alt="New branch" title="New branch" /></a>
</div>



<div id="navigation">
<?php include 'navigation.phtml' ?>
</div>
</div>

<div id="center">

<div id="newfile" class="hidden">
<?php echo $this->newFileForm ?>
</div>
<div id="newdir" class="hidden">
<?php echo $this->newDirForm ?>
</div>
<div id="newbranch" class="hidden">
<?php echo $this->newBranchForm ?>
</div>

<div class="title">
<?php echo $this->escape( $this->editing ); ?>
</div>
<form id="editorForm" method="post" action="/">
<div id="codeBorder">
<textarea name="code" id="code" rows="25" cols="80"><?php echo $this->escape($this->content); ?></textarea>
</div>
<p>
<input type="submit" name="save" value="Save" />
<input type="submit" name="commit" value="Commit" />
<input type="text" name="commitMessage" id="commitMessage" class="inputtext" />
</p>
</form>
<?php echo $this->result; ?>
<script type="text/javascript">
//<![CDATA[
dojo.addOnLoad(init);
//]]>
</script>

</div>

<div id="footer">
</div>