<form id="editorForm" method="post" action="/">
<div id="codeBorder">
<textarea name="code" id="code" rows="25" cols="80"><?php echo $this->escape($this->content); ?></textarea>
</div>
<p><input type="text" name="commitMessage" class="inputtext" />
<input type="submit" name="Commit" value="Commit" /></p>
</form>
<?php echo $this->result; ?>
<script type="text/javascript">
//<![CDATA[
dojo.addOnLoad(init);
//]]>
</script>