<div class="title"><p>Merge</p><p>Local branches:</p></div>
<ul class="list" id="locals">
<?php
if( count($this->branches) > 0 )
{
    foreach( $this->branches as $branch )
    {
        if( $branch != $this->branch )
        {
            echo '<li class="merge">
            <a href="?merge='.urlencode( $branch ).'">'.$this->escape( $branch )."</a>
            </li>\n";
        }
    }
}
?>
</ul>

<div class="title"><p>Pull</p><p>Tracked remote branches:</p></div>
<ul class="list" id="remotes">
<?php
if( count($this->remotes) > 0 )
{
    foreach( $this->remotes as $remote )
    {
        echo '<li class="pull">
            <a href="?pull='.urlencode( $remote ).'">'.$this->escape( $remote )."</a>
            </li>\n";
    }
}
?>
</ul>

<div class="title"><p>Add remote</p><p>Available remote sources:</p></div>
<ul class="list" id="avail">
<?php
if( count($this->avail) > 0 )
{
    foreach( $this->avail as $uid => $user  )
    {
        echo '<li class="avail">
            <a href="?avail='.urlencode( $uid ).'">'.$this->escape( $user )."</a>
            </li>\n";
    }
}
?>
</ul>
