<div class="title"><p>Merge with</p></div>
<ul class="list">
<?php
if( count($this->branches) > 0 )
{
    foreach( $this->branches as $branch )
    {
        if( $branch != $this->branch )
        {
            echo '<li class="merge">
            <a href="?merge='.urlencode( $branch).'">'.$this->escape($branch)."</a>
            </li>\n";
        }
    }
}
?>
</ul>

<div class="title"><p>Tracked remotes</p></div>
<ul class="list">

</ul>

<div class="title"><p>Available remote sources</p></div>
<ul class="list">

</ul>
