<div class="title">
<p><?php echo $this->escape($this->branch) ?></p>
</div>

<ul class="list">
<?php
if( count($this->branches) > 0 )
    foreach( $this->branches as $branch )
    {
        echo '<li class="branch"><a href="?branch='.urlencode( $branch ).'">'.$this->escape($branch)."</a></li>\n";
    }
?>
</ul>

<div class="title">
<p><?php echo $this->escape($this->path) ?></p>
</div>
<ul class="list">
<?php if( strlen($this->path) > 1 ) {?>
<li class="updir"><a href="?updir=1">Up dir ..</a></li>
<?php } ?>
<?php
if( count( $this->files['dirs'] ) > 0 )
    foreach( $this->files['dirs'] as $file )
    {
        echo '<li class="dir"><a href="?dir='.urlencode( $file ).'">'.$this->escape($file)."</a></li>\n";
    }
if( count( $this->files['files'] ) > 0 )
    foreach( $this->files['files'] as $file )
    {
        echo '<li class="file"><a href="?file='.urlencode( $file ).'">'.$this->escape($file)."</a></li>\n";
    }
?>
</ul>
