<div id="projectWindow">
<?php include 'menu.phtml' ?>
<h1>Open project</h1>
<?php
if( count($this->projects) > 0 ) { ?>
<ul id="projectList">
<?php
    foreach( $this->projects as $p )
    {
        echo '<li><a href="?pro=' . urlencode( $p['pid'] ) . '">' . $this->escape($p['name']) . '</a></li>' ;
    }
}
else
{
?>
    <p>No projects assigned to current user.<br />
    <a href="/project/join/">Join</a> a project or create a <a href="/project/new/">new</a> one.</p>
<?php
}
?>
</ul>
</div>